import { Property } from "@/store/propertyStore";

export const ALL_MOCK_PROPERTIES: Property[] = [
  {
    id: "p1",
    title: "Vasantham Premium Gold Villa",
    slug: "vasantham-premium-gold-villa",
    description: "Elegant 4 BHK luxury villa in Akkarai, ECR with panoramic sea breezes. Complete DTCP and RERA verification. 24/7 security, high-end security system, swimming pool, landscape garden, power backup, water treatment plant, solar electric panels, and private automated garage.",
    price: 18500000, // 1.85 Cr
    purpose: "buy",
    city: "Chennai",
    locality: "ECR, Akkarai",
    type: "Villa",
    bedrooms: 4,
    bathrooms: 4,
    areaSqFt: 3600,
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=800&q=80"
    ],
    status: "ready-to-move",
    isRERAApproved: true,
    isDTCPApproved: true,
    isVerified: true,
    isFeatured: true,
    isVaastuCompliant: true,
    isFloodSafe: true,
    furnished: "Yes",
    postedDate: "2026-05-15",
    views: 324,
    waterAvailability: "24 Hours Borewell & Metro Water",
    ebConnection: "3 Phase Connection",
    roadWidth: "40 Feet",
    drainage: "Underground Drainage System",
    pattaNumber: "Patta No: 345/2025",
    reraNumber: "TN/01/Building/3482/2024",
    cmdaStatus: "CMDA Approved Layout",
    agent: {
      name: "Suresh Kumar",
      agency: "Chennai Luxury Realty",
      rating: 4.9,
      deals: 124,
      avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80",
      phone: "+91 98400 12345",
      whatsapp: "+919840012345"
    }
  },
  {
    id: "p2",
    title: "Marutham Royal Heights",
    slug: "marutham-royal-heights",
    description: "Premium 3 BHK high-rise apartment in the heart of Coimbatore at Race Course. Luxury amenities including infinity pool, fully equipped clubhouse, automated glass elevators, smart home control hub, air-conditioned fitness studio, and children's recreation park.",
    price: 12000000, // 1.2 Cr
    purpose: "buy",
    city: "Coimbatore",
    locality: "Race Course",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 3,
    areaSqFt: 2200,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80"
    ],
    status: "ready-to-move",
    isRERAApproved: true,
    isDTCPApproved: false,
    isVerified: true,
    isFeatured: true,
    isVaastuCompliant: true,
    isFloodSafe: true,
    furnished: "Semi",
    postedDate: "2026-05-10",
    views: 215,
    waterAvailability: "Siruvani & Borewell Water Available",
    ebConnection: "3 Phase Connection",
    roadWidth: "60 Feet",
    drainage: "Corporation Drainage",
    pattaNumber: "Patta No: 182/2023",
    reraNumber: "TN/11/Building/0023/2023",
    cmdaStatus: "N/A - Coimbatore Corporation Approved Layout",
    agent: {
      name: "Arun Prasath",
      agency: "Kovai Homes Ltd",
      rating: 4.8,
      deals: 98,
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
      phone: "+91 98940 54321",
      whatsapp: "+919894054321"
    }
  },
  {
    id: "p3",
    title: "Nellai Majestic Meadows",
    slug: "nellai-majestic-meadows",
    description: "Premium DTCP approved housing plot at KTC Nagar, Tirunelveli. Prime locality close to national highway. Excellent high return investment property for immediate construction.",
    price: 4500000, // 45 L
    purpose: "buy",
    city: "Tirunelveli",
    locality: "KTC Nagar",
    type: "Plot",
    bedrooms: 0,
    bathrooms: 0,
    areaSqFt: 2400,
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80"
    ],
    status: "plot",
    isRERAApproved: false,
    isDTCPApproved: true,
    isVerified: true,
    isFeatured: false,
    isVaastuCompliant: true,
    isFloodSafe: true,
    furnished: "No",
    postedDate: "2026-05-18",
    views: 89,
    waterAvailability: "Borewell Water Source",
    ebConnection: "Direct EB Line Available",
    roadWidth: "30 Feet",
    drainage: "Open Drainage",
    pattaNumber: "Patta No: 891/2026",
    reraNumber: "N/A",
    cmdaStatus: "N/A - Tirunelveli DTCP Office Approved",
    agent: {
      name: "Murugan Selvam",
      agency: "Nellai Real Estate",
      rating: 4.7,
      deals: 64,
      avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80",
      phone: "+91 94430 98765",
      whatsapp: "+919443098765"
    }
  },
  {
    id: "p4",
    title: "Temple View Residency",
    slug: "temple-view-residency",
    description: "Modern 2 BHK apartment near Madurai Meenakshi Temple. Fully Vaastu compliant, semi-furnished ready to occupy.",
    price: 6800000, // 68 L
    purpose: "buy",
    city: "Madurai",
    locality: "K.K. Nagar",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    areaSqFt: 1100,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80"],
    status: "ready-to-move",
    isRERAApproved: true,
    isDTCPApproved: true,
    isVerified: true,
    isFeatured: false,
    isVaastuCompliant: true,
    isFloodSafe: true,
    furnished: "Semi",
    postedDate: "2026-05-02",
    views: 154,
    waterAvailability: "Cauvery & Borewell Connections",
    ebConnection: "3 Phase connection",
    roadWidth: "33 Feet",
    drainage: "City Sewage Connection",
    pattaNumber: "Patta No: 442/2024",
    reraNumber: "TN/12/Building/4921/2024",
    cmdaStatus: "N/A - Madurai Corporation Approved",
    agent: {
      name: "Ramanathan M.",
      agency: "Pandian Promoters",
      rating: 4.8,
      deals: 112,
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
      phone: "+91 98420 56789",
      whatsapp: "+919842056789"
    }
  },
  {
    id: "p5",
    title: "Premium Commercial Complex",
    slug: "premium-commercial-complex",
    description: "Commercial space suitable for offices or retail showrooms. Prime road facing spot on OMR, Chennai.",
    price: 35000000, // 3.5 Cr
    purpose: "buy",
    city: "Chennai",
    locality: "OMR, Thoraipakkam",
    type: "Commercial",
    bedrooms: 0,
    bathrooms: 4,
    areaSqFt: 4800,
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"],
    status: "ready-to-move",
    isRERAApproved: true,
    isDTCPApproved: false,
    isVerified: true,
    isFeatured: true,
    isVaastuCompliant: false,
    isFloodSafe: true,
    furnished: "No",
    postedDate: "2026-04-20",
    views: 412,
    waterAvailability: "Metro Water Service",
    ebConnection: "High Tension EB Connection",
    roadWidth: "80 Feet",
    drainage: "Underground Sewage",
    pattaNumber: "Patta No: 120/2022",
    reraNumber: "TN/02/Commercial/5021/2022",
    cmdaStatus: "CMDA Approved Structure",
    agent: {
      name: "Suresh Kumar",
      agency: "Chennai Luxury Realty",
      rating: 4.9,
      deals: 124,
      avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80",
      phone: "+91 98400 12345",
      whatsapp: "+919840012345"
    }
  },
  {
    id: "p6",
    title: "Luxury Beachfront Villa ECR",
    slug: "luxury-beachfront-villa-ecr",
    description: "Stunning architectural marvel beachfront property in ECR. Ultimate luxury. Infinity pool, custom Italian kitchen, automated glass walls.",
    price: 49000000, // 4.9 Cr
    purpose: "buy",
    city: "Chennai",
    locality: "ECR, Uthandi",
    type: "Villa",
    bedrooms: 5,
    bathrooms: 6,
    areaSqFt: 5800,
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80"],
    status: "ready-to-move",
    isRERAApproved: true,
    isDTCPApproved: true,
    isVerified: true,
    isFeatured: true,
    isVaastuCompliant: true,
    isFloodSafe: true,
    furnished: "Yes",
    postedDate: "2026-05-19",
    views: 589,
    waterAvailability: "Borewell & RO Plant Installed",
    ebConnection: "3 Phase Connection + 100% Generator Backup",
    roadWidth: "30 Feet Private Road",
    drainage: "Integrated Soak Pit System",
    pattaNumber: "Patta No: 994/2026",
    reraNumber: "TN/01/Building/1204/2025",
    cmdaStatus: "CMDA Approved Layout",
    agent: {
      name: "Suresh Kumar",
      agency: "Chennai Luxury Realty",
      rating: 4.9,
      deals: 124,
      avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80",
      phone: "+91 98400 12345",
      whatsapp: "+919840012345"
    }
  },
  {
    id: "p7",
    title: "Cozy 2BHK Rental Apartment Erode",
    slug: "cozy-2bhk-rental-apartment-erode",
    description: "Fully furnished 2 BHK apartment for rent in Erode. Near bus stand, highly convenient, ideal for families.",
    price: 18000, // 18k / month
    purpose: "rent",
    city: "Erode",
    locality: "Perundurai Road",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    areaSqFt: 1000,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80"],
    status: "ready-to-move",
    isRERAApproved: false,
    isDTCPApproved: true,
    isVerified: true,
    isFeatured: false,
    isVaastuCompliant: true,
    isFloodSafe: true,
    furnished: "Yes",
    postedDate: "2026-05-11",
    views: 45,
    waterAvailability: "Corporation Metro Connection",
    ebConnection: "Single Phase Connection",
    roadWidth: "30 Feet",
    drainage: "Corporation Sewage Line",
    pattaNumber: "N/A - Rental",
    reraNumber: "N/A - Rental",
    cmdaStatus: "N/A - Erode Corporation approved",
    agent: {
      name: "Prakash Raj",
      agency: "Erode Housing Advisors",
      rating: 4.6,
      deals: 42,
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
      phone: "+91 94440 23456",
      whatsapp: "+919444023456"
    }
  }
];
